version: '3'
services:
  app: 
    build: .
    container_name: educase-app
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/educase
      - JWT_SECRET=your_jwt_secret_here
      - NODE_ENV=development
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: educase
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    
volumes: 
  mysql_data: 